### ISSUE TITLE
Copying from hexchat does not work

### ISSUE THREAD

**Issue by lenny87** [hexchat/hexchat#1137]
When I select some text in HexChat and try to copy it with ctrl+C keystroke, nothing happens and old copied text (or nothing) will remain in paste buffer.

Version: HexChat 2.10.1 (from Arch Linux package)
Compiled: Jul 29 2014
OS: Linux 3.16.2-1-ck [x86_64/1,40GHz/SMP]
OS: Arch Linux x64

**Comment by kparal** [comment]
Since multiple users complain about this, isn't it possible to simply listen for ctrl+c keypress, and if that happens, copy the **text selection** into the clipboard? I.e. handle the ctrl+c shortcut manually, because of this always-active input box?

**Comment by TingPing** [comment]
@kparal You could do some hacky workaround like "if no selection in input, but ctrl+c pressed, and selection in xtext, then copy that".. but that is so unclear and un-obvious it just makes the situation worse. xtext was designed stupidly, thats just all there is to it and it wont be changing any time soon.

**Comment by kparal** [comment]
Why is it unobvious and why does it make the situation worse?

* If I press Ctrl+C, it's obvious I want to copy something. If there's nothing selected in the input box, and there's something selected in chat, that's what I want to copy, you can't go wrong here. The only complicated situation is when both input box and chat have some selection active. Then, I assume, input box would be preferred. It makes sense from the user point of view and it is easy to correct.

* About the situation being better or worse - currently, I hit ctrl+c and nothing happens. I've been using xchat/hexchat for several years now, and I still do it **daily**. And I'm daily angry about it. Ctrl+C is just a reflex, you don't think about it. If you implement this, it will do the right thing in 99% of times, and that's what I call a great improvement.

Please note that you can still keep the ctrl+shift+c shortcut in place, for those who are used to it and/or want to always be sure they copy from chat. I'm not asking to replace it. Just to make the world-known ctrl+c work as expected, at least in majority of cases.

**Comment by TingPing** [comment]
Ok support situation:

Current:
> "How do I copy text?"
> "Select it, or press ctrl+shift+c"

Not normal, but simple, understandable, etc.

With proposed behavior:
> "How do I copy text?"
> "well if this then that but if this then something else but if that then this... just hit ctrl+shift+c"

It is a mess unless you have an understanding of the stupid hacks at work.

I agree the current behavior is stupid, I hate everything (literally) about xtext. I wish it would go die and HexChat moved into the technology of the 1990s already, but here we are with a 16 year legacy of behavior.

**Comment by kparal** [comment]
I understand your concern about user support, I just think it's not going to happen. If I hit Ctrl+C and find out that I haven't copied something from the chat but from the input box, I think it's quite obvious to anyone - deselect/clear input box and try again. I don't think anyone will come asking.

When I compare it to the question "why doesn't Ctrl+C work in hexchat?", I think that one is much more non-obvious and harder to find out the answer to. You most probably have to search online for it.

We're also talking about something that is disabled by default (autocopy is enabled by default). Since the user needs to enable this behavior manually, there can be a lot of done about it to make it clearer, e.g. name the option properly, e.g.

```
(o) Use mouse selection to copy text to clipboard automatically
( ) Use Ctrl+C to copy selected text either from input box or chat area
```

and of course a tooltip can be used to explain it properly.

I simply think that this change would improve the user friendliness a lot and the mentioned drawbacks are not such a big deal, i.e. net win. But you're the maintainer here, I'm not. If you decide not to make any adjustments but know about some potential plugins that could help users like me, I'd be very grateful to hear about them. Alternatively, if someone else writes such a plugin in the future, please post a link here. Thanks in advance.

**Comment by RichardHitt** [comment]
A tooltip, hmm.  Usually tooltips are exposed as a result of hovering.  
What would I hover over to get a tooltip displayed, in your scenario?

And, tingping, you're being too harsh on xtext, as you know.  You have 
made improvements and helped clean it up.  I have done likewise.  You 
and I together have managed to make work properly just about all text 
highlighting, including italics.  I'm working on a non-English-alphabet 
performance improvement that will make hexchat usable for more people.  
Etc etc.  So don't be so harsh about xtext, please.

Richard Hitt

**Comment by TingPing** [comment]
@RichardHitt I'm not being harsh on your improvements, xtext almost displays text properly, so we really have done good things. That doesn't mean it shouldn't be replaced.

**Comment by kparal** [comment]
> A tooltip, hmm. Usually tooltips are exposed as a result of hovering. What would I hover over to get a tooltip displayed, in your scenario?

The same item that currently already has a tooltip :) Which is the following checkbox in options:
> [  ] Automatically copy selected text

If you hover over if, there is an explanation tooltip that talks about the ctrl+shift+c shortcut if it is disabled.

I assumed a similar tooltip could be added over the radion button I proposed. It could even still mention ctrl+shift+c for those who always want to be sure to copy from chat area (also to be consistent with older versions and people used to it).

**Comment by lenny87** [comment]
I can recommend also one more solution for that - If I select text in chat window, copy action should be accessible from right-click menu. But ctrl+c will be best as guys already sseid there.

**Comment by Poorchop** [comment]
I don't see the problem with ctrl+shift+C. I'm pretty that is the standard keybinding for copying text in most terminal emulators, while ctrl+C breaks the current active process. I also like HexChat's default behavior of automatically copying selected text to the clipboard - a lot of times, I will highlight text in another program and then ctrl+V somewhere else, only to realize that in this case, I have to ctrl+C first.

I can definitely understand why some people would want to disable the automatic copy to clipboard behavior, but with the way that HexChat currently works, ctrl+shift+C makes the most sense. I think the "if no selection in input" hacky workaround wouldn't even be a good solution because that means users have to first delete the contents of the input box in order to select chat window text.

>I think that one is much more non-obvious and harder to find out the answer to. You most probably have to search online for it.

You have to search online in order to figure out how to do a lot of things, including multiple things in HexChat. That's why there is extensive documentation that anyone can edit, as well as an IRC channel that is active around the clock. You could also just go to "Window" in the HexChat menu bar, where you will see the "copy selection" option and the corresponding shortcut.

**Comment by kparal** [comment]
> I'm pretty that is the standard keybinding for copying text in most terminal emulators, while ctrl+C breaks the current active process.

Yes, it is. Hexchat is a chat, though, which falls in to the "everything else" category.

> I also like HexChat's default behavior of automatically copying selected text to the clipboard

I don't propose to remove it nor make it not the default behavior.

>  I think the "if no selection in input" hacky workaround wouldn't even be a good solution because that means users have to first delete the contents of the input box in order to select chat window text.

No *selection*, not *content*.

> You have to search online in order to figure out how to do a lot of things, including multiple things in HexChat. 

If just a single search worked for me, I would have never spent the time reporting this issue. I'm fighting with it daily. I'm happy that it works for you. But it seems you're not using the manual copy behavior anyway. I'm not sure how it would affect you if Ctrl+C shortcut was added?

**Comment by TingPing** [comment]
>I'm not sure how it would affect you if Ctrl+C shortcut was added?

You mean overridden, that is the questionable part.

xtext is very much designed like a terminal window. Until hexchat improvements it basically only could use monospace fonts, it also only had a select to copy behavior, etc.

**Comment by Poorchop** [comment]
>No selection, not content.

Well since you cleared that up, I guess you make a decent case. The hacky workaround might not be such a bad idea then, even though it would be kind of ugly. I still don't see why it's so hard to adapt to just using ctrl+shift+C - if you can do it in your terminal emulator, then you can get used to doing it in another program that more or less looks and feels like a terminal program (by default). I don't feel as strongly about it since I actually like the default select-to-copy behavior, but I can see where you are coming from now.

**Comment by kparal** [comment]
> You mean overridden, that is the questionable part.

I already mentioned twice I don't ask to replace it: https://github.com/hexchat/hexchat/issues/1137#issuecomment-104673897 and https://github.com/hexchat/hexchat/issues/1137#issuecomment-104735216

>  I still don't see why it's so hard to adapt to just using ctrl+shift+C

Believe me, I really tried (and still try). I opened #1380 because during an IRC conversation I quickly selected a sentence from a different channel, hit Ctrl+C as I'm used to from everywhere else (which in reality did nothing), switched to the other channel, pasted using Ctrl+V and hit Enter. Only after that I found out that what I pasted was an older clipboard contents, which wasn't meant to go public... and this wasn't the first time.

It's not like it's not possible to remember ctrl+shift+c. Sometimes I do, sometimes I don't, but it's easy to correct. But occasionally such accidents happen and they are not pleasant. Also, using hexchat keeps me on my toes, because I constantly need to think about "the copy exception rule". These operations then feel unreliable to me, because I'm not able to be constantly mentally aware whether I'm using hexchat, gedit, firefox, atom, spyder, pidgin or one of the dozen other apps I switch between every few minutes. So I'm being unhappy about that.

As for terminal, yeah, for some reason I'm usually able to keep those special shortcuts in my mind. But more often than not, I simply use the mouse context menu. I find ctrl+shift+c hard to press and there's a danger that if you press shift too little, you'll kill your program, so I don't use it much.

> if you can do it in your terminal emulator, then you can get used to doing it in another program that more or less looks and feels like a terminal program

That's probably the difference between us. Subconsciously, I consider hexchat exactly the same as any other IM or chat. Or any other GUI app. It has white background, you know... and terminal is black :-) It has probably been hard-wired into my brain over the years. Not sure if it is about the color or just general look and feel.

**Comment by deckblad** [comment]
Hexchat should use whatever hotkey is common for that OS. Like every other program.

**Comment by Arnavion** [comment]
>Focus shouldn't be locked to the text box. If I'm selecting something, that's where the cursor now. If I want to type, I click back in the input box.

For the record, this would be a severe usability regression for anyone who has HC running on another monitor and wants to quickly focus it and start typing.

**Comment by kparal** [comment]
> For the record, this would be a severe usability regression for anyone who has HC running on another monitor and wants to quickly focus it and start typing.

Not really, since hexchat can auto-focus the input box once you start typing.

**Comment by eos-** [comment]
@kparal 
> If I press Ctrl+C, it's obvious I want to copy something. If there's nothing selected in the input box, and there's something selected in chat, that's what I want to copy, you can't go wrong here. The only complicated situation is when both input box and chat have some selection active. Then, I assume, input box would be preferred. It makes sense from the user point of view and it is easy to correct.

I implemented exactly this with a little patch in `menu.c`. Enjoy! I know I will. :)
[ctrl-c-patch.txt](https://github.com/hexchat/hexchat/files/1908695/ctrl-c-patch.txt)

**Comment by rzumer** [comment]
I agree that this is very bothersome. On top of that Ctrl+Shift+C often does not even work at all. For example it doesn't seem to work to copy text in the input bar, and sometimes for no discernible reason I have to re-select text in order for copying to do anything. It's very frustrating and makes no sense from the user's perspective and I agree that Ctrl+C should work universally.

**Comment by varshneydevansh** [comment]
I am a bit late here but `ctr+shft+c` is not that wrong as in Linux terminal this is the only way to copy certain text and if we try doing `ctrl+c` in terminal it's treat as cancelling the running command.
