### ISSUE TITLE
Can't open log file(s) for writing

### ISSUE THREAD

**Issue by dovah-chan** [hexchat/hexchat#1269]
![ss 2015-01-14 at 04 23 38](https://cloud.githubusercontent.com/assets/10537901/5747953/11b726ac-9c0a-11e4-9df0-eb5cb5ef85fa.png)

This issue occurs when trying to use the log feature in build 2.10.2 and previous versions. Upon clicking OK the client will then stop working and then I am forced to close the window. But if I don't hit OK the client will be perfectly stable, albeit unable to be interacted with as one is not allowed to interact with the main window until the other one is gone. (which causes the crash) 

I've tried editing permissions on the log file for the server that is causing the issue and running hexchat in admin mode but nothing seems to work. Server address is irc.tsukihi.me if anyone is wondering

**Comment by Arnavion** [comment]
What's your irc_logmask pref?

**Comment by dovah-chan** [comment]
irc_logmask = %n\%c.log

also: http://pastebin.com/xsgvXFsn 

if there is anything else you need to see just feel free to ask

**Comment by Arnavion** [comment]
You have a trailing space after the network name. Remove it in the network preferences and it shouldn't crash any more.

There's two bugs here though:
- Being unable to open a log file causes a crash.
- Filenames with a trailing space in the directory results in being unable to open the log file.

**Comment by Arnavion** [comment]
The first issue is fixed by the above commit.

The second issue is more involved. We use g_mkdir_with_parents to make the directory structure where the log file is going to live. g_mkdir_with_parents uses GetFileAttributes on Windows to test if the directory exists. This function ignores trailing spaces in the directory name. As a result if you already have a directory `C:\foo\bar\` and you're trying to write `C:\foo \bar\baz.log`, this function will not create `C:\foo \` and `C:\foo \bar\` because it will see that `C:\foo\` and `C:\foo\bar\` already exist.

This is a known issue with GetFileAttributes - Google returns some hits like [this one.](https://forum.filezilla-project.org/viewtopic.php?t=32804#p122056). I haven't looked if there's an alternative to fix this, but either way this is an issue with glib so it won't be fixed here.

Just don't create log filenames with leading or trailing spaces in the path components, as you accidentally did here.

**Comment by dovah-chan** [comment]
Okay :) thank you very much sweetie for the quick response! It seems to work and log fine now. I sure hope no one else has fallen victim to same silly mistake as I did X__X Just glad its documented now though.

**Comment by HoratioSanchez** [comment]
Hi, I have this problem too and how do I apply this fix?

**Comment by TingPing** [comment]
@HoratioSanchez:
- Windows: https://dl.hexchat.net/hexchat/testing
- Linux: https://hexchat.readthedocs.org/en/latest/building.html#unix
