### ISSUE TITLE
removing of IRC encoding breaks a lot of networks

### ISSUE THREAD

**Issue by DerPate** [hexchat/hexchat#1275]
commit SHA: ee17ec6b4f0d0d198f0a8efa1eaf4e93646140e1 breaks a lot of IRCDs runnig inspiircd or old unreal ircds which are still using the ircd encoding.

**Comment by Mikaela** [comment]
IRC doesn't have encoding, users are free to use whatever encoding they wish and the only way to force specific encoding is kbanning users not using proper encodings.

If you mean that settings get broken, because those networks were removed, HexChat should automatically change charset from IRC to UTF-8.

**Comment by TingPing** [comment]
"IRC" was never a real encoding.

**Comment by Arnavion** [comment]
>If you mean that settings get broken, because those networks were removed, HexChat should automatically change charset from IRC to UTF-8.

It does do so. UTF-8 is the default for new servers, and all unrecognized server encodings (including "IRC") are changed to UTF-8 as well. (There is still one unmerged commit for doing this for unrecognized network encodings as well.)

**Comment by Mikaela** [comment]
I see. I don't understand what this issue was about then.

**Comment by DerPate** [comment]
the issue is that removing this encoding it breaks the umlaute for german users on the most ircd which where user are using iso-8856-15 or utf-8 in the same time so you see just gibberisch or the utf-8 missing gylph symbol.

**Comment by TingPing** [comment]
UTF8 has been the default in HexChat for a significant time now and "IRC" only existed in [he]xchat. If most of a network actually relied upon that encoding then they already have problems. Users should pick a real encoding and stick with it.

**Comment by Arnavion** [comment]
If the problem is with mixed iso-8859-15 and utf-8, then this commit isn't even relevant. It's https://github.com/hexchat/hexchat/commit/5749c53 Before that commit, HC would try to interpret as UTF-8 and [fall back to system locale-dependent encoding on failure](https://github.com/hexchat/hexchat/commit/5749c53#diff-9936d10a48c5674f2a724f3fed86797aL880) (and I assume German locale's default encoding is iso-8859-15).

If you want umlauts, set your network encoding to iso-8859-15 or iso-8859-1 or utf-8. If you want both umlauts and utf-8 characters, set your network encoding to utf-8. Either way, all clients have to agree on an encoding to be able to make sense of each other.
