### ISSUE TITLE
Do not show notification if focus in window (or tab)

### ISSUE THREAD

**Issue by poxip** [hexchat/hexchat#1278]
Even if HexChat's main window is focused (for example I talk on /query) I'm getting notifications on and about any message from the conversation..In my humble opinion showing those notifications is pointless and annoying. So What I propose is just to do not show notifications from current conversation (tab - of course if the window has focus!).
__System__: GNU/Linux Ubuntu 14.10 
__Desktop Environment__: Gnome-Shell 3.14.3
__HexChat version:__ 2.10.0

**Comment by TingPing** [comment]
Preferences > Alerts > Omit alerts while the window is focused.

**Comment by Arnavion** [comment]
@TingPing Maybe leaving that setting unchecked should still omit alerts if the window is focused and the alert source is the current tab?

**Comment by poxip** [comment]
Oo, sorry. But shouldn't it be checked by default? That's what I think about it.

**Comment by TingPing** [comment]
@poxip As you can imagine the setting is quite opinionated. It would appear to me that having them disabled based on focus is more confusing to many users and causes more complaints than otherwise. The setting exists for those who want to actively make it more quiet but at least it is clear alerts are not broken.

@Arnavion That sounds like a new option.

**Comment by poxip** [comment]
Ok, that makes sense.

Śr., 28 sty 2015, 03:19 TingPing użytkownik <notifications@github.com>
napisał:
