### ISSUE TITLE
Crash when OpenSSL 1.0.2a libeay32.dll is loaded

### ISSUE THREAD

**Issue by MoodyMoon** [hexchat/hexchat#1326]
HexChat safe mode doesn't work too. Here is the crash message: "The ordinal 4684 could not be located in the dynamic link library LIBEAY32.dll.".

HexChat version is 2.10.2.

Hopefully there is a hotfix for this. As always, thanks for your hard work.

**Comment by TingPing** [comment]
HexChat doesn't ship with that version so either you installed it or something else is messing with your PATH. Only the version bundled is supported.

**Comment by MoodyMoon** [comment]
Just for future reference. Renaming "ssleay32.dll" and "libeay32.dll" in the HexChat folder to something else forces HexChat to use the OpenSSL library in the system folder and it works. My problem is caused by "ssleay32.dll" and "libeay32.dll" not having the same version. A newer version of the former is being loaded from the system folder because the copy in the HexChat folder has a file name "ssleay32.ignore.dll" and the latter is being loaded from the HexChat folder which is an older version. HexChat does work with newer versions of OpenSSL but of course not supported officially.

**Comment by Arnavion** [comment]
1. You deliberately forced the version mismatch by renaming ssleay32.dll to ssleay32.ignore.dll, thus creating the problem in the first place.
1. If you have openssl installed in your system directory, you have bigger problems. Nothing should be placing openssl DLLs into the system directory. Perhaps you did it yourself.
1. It is not as simple as "HexChat does work with newer versions of OpenSSL" since it depends on how that other openssl was compiled. Not only is it not officially supported, it is detrimental to your security to do such things without knowing what you're doing, as evidently you don't.

The openssl that HC uses is already up-to-date (1.0.1m). There is no benefit (security or otherwise) from forcing it to use the 1.0.2 series.

**Comment by MoodyMoon** [comment]
1. Actually, I didn't but I am not sure what did it (Certainly not malware, I am quite sure of that). It certainly did cause the problem in the first place.
2. I did that myself by installing https://slproweb.com/download/Win32OpenSSL_Light-1_0_2a.exe. The link is actually obtained from https://www.openssl.org/about/binaries.html. Even mIRC OpenSSL installers place the libraries in the system folder. http://www.mirc.com/ssl.html
3. I was under the impression that stable OpenSSL releases announced on the official OpenSSL site are always better than older versions since they patched up security holes. Well, to be honest, I didn't realize there might security issues when doing that and obviously you have more experience in that aspect.

It is just a habit of mine to keep everything up-to-date for better or worse.

**Comment by TingPing** [comment]
>I was under the impression that stable OpenSSL releases announced on the official OpenSSL site are always better than older versions since they patched up security holes.

OpenSSL currently has 3 supported branches. 0.9.8, 1.0.1, and 1.0.2. Despite the extremely terrible numbering system these are all very different releases and all are supported for security fixes. Forcing HexChat from the latest 1.0.1 release to 1.0.2 release doesn't do anything for security and it doesn't do anything for features really since it doesn't make use of the new things.

**Comment by Arnavion** [comment]
>I did that myself by installing https://slproweb.com/download/Win32OpenSSL_Light-1_0_2a.exe. The link is actually obtained from https://www.openssl.org/about/binaries.html.

And that is wrong. As I already told you, it matters how the library is compiled. If a library is not compiled with the exact same compiler and CRT as HC is, then using it with HC will lead to crashes at best and silent security issues at worst.

>Even mIRC OpenSSL installers place the libraries in the system folder. http://www.mirc.com/ssl.html

And it's doing it wrong. Application-specific libraries should never be installed in system directories, for precisely the reason that they're application-specific.

>I was under the impression that stable OpenSSL releases announced on the official OpenSSL site are always better than older versions since they patched up security holes.

Correct. And 1.0.1m is the latest release in the 1.0.1 series, and that is what HC uses.

**Comment by MoodyMoon** [comment]
I get it now. Thanks for the help.
