### ISSUE TITLE
Issue unsetting away command

### ISSUE THREAD

**Issue by joelj7** [hexchat/hexchat#1343]
Hi,

Inspircd 2.0.18 + HexChat 2.10.2.

As per: https://github.com/thepaul/inspircd-deb/blob/master/docs/rfc/rfc1459.txt

Sending an empty /away command should unmark as away - this does not appear to be case with HexChat, you instead get the following:

```
Already marked away: .
Usage: AWAY [<reason>], sets you away
```

Sending a /quote away to the server works as intended.

**Comment by KindOne-** [comment]
Kinda sure you can use ```/back``` to turn off the ```/away```.

**Comment by Arnavion** [comment]
Allowing an /AWAY without a reason might confuse people who would expect it to set them as away without a reason. Just because the underlying protocol message is AWAY with no parameters doesn't mean the user command has to be the same - it makes sense for the protocol message to overload a message type based on the presence or absence of a parameter.

As @KindOne- said, /BACK will send an AWAY with no parameters.

**Comment by Mikaela** [comment]
> Allowing an /AWAY without a reason might confuse people who would expect it to set them as away without a reason.

This again confuses users who are more familiar with IRC protocol as

>  Just because the underlying protocol message is AWAY with no parameters

But if the user is supposed to use `/back` instead to unset their away status, the help text has an issue.

```
Already marked away: .
Usage: AWAY [<reason>], sets you away
```

`[<reason>]` means "optional reason" to most of people and it should be just `<reason>`.

**Comment by TingPing** [comment]
@Mikaela Yea I agree the help text could use improving.

**Comment by Arnavion** [comment]
Okay, change it to `Usage: AWAY <reason>, sets you away. Use /BACK to clear.` or something.
