### ISSUE TITLE
Hexchat doesn't auto resolve ip reverse to verify ssl certificate

### ISSUE THREAD

**Issue by trippleflux** [hexchat/hexchat#1372]
It seems hexchat doesn't automatically resolve ip reverse, hence when connecting to irc server through ip (ssl), hexchat failed to verify the certificate because of hexchat doesn't know the hostname.

If connecting through hostname (irc.domain.com) hexchat able to verify the certificate, please add auto resolving ip reverse when connecting into irc server through IP, so hechat able to verify the certificate.

**Comment by trippleflux** [comment]
Here is the error i am getting at when connecting through IP to the irc server : 
* Looking up 195.154.134.226
* Connecting to 195.154.134.226:6697 (195.154.134.226:6697)
* * Certification info:
*   Subject:
*     OU=GT68757583
*     OU=See www.rapidssl.com
*     resources
*     cps (c)15
*     OU=Domain Control Validated - RapidSSL(R)
*     CN=*.prodigy.ninja
*   Issuer:
*     C=US
*     O=GeoTrust Inc.
*     CN=RapidSSL SHA256 CA - G3
*   Public key algorithm: rsaEncryption (4096 bits)
*   Sign algorithm sha256WithRSAEncryption
*   Valid since May  9 15:40:09 2015 GM to May 11 13:05:18 2016 GM
* * Cipher info:
*   Version: TLSv1/SSLv3, cipher ECDHE-RSA-AES256-GCM-SHA384 (256 bits)
* Connection failed (* Verify E: Failed to validate hostname? (-1))

**Comment by Mikaela** [comment]
Certificates are meant for domains, not IP addresses and I think this issue is invalid as client isn't even supposed to check reverse DNS.

Your certificate is also invalid for the mentioned certificate, because of`CN=*.prodigy.ninja` and reverse DNS for `195.154.134.226` is `prodigy.ninja` which means that your certificate is only valid for subdomains, not the domain itself.

**Comment by trippleflux** [comment]
Just noticed now on how the certificate works, my mistakes.

**Comment by kfogel** [comment]
For what it's worth, I got a similar error when connecting to Freenode.net IRC, and the solution was to uncheck "Use SSL for all the servers on this network" in the settings reachable via Network List -> Freenode -> Edit.

I'm mentioning this here because this issue comes up in search results for the problem I encountered, even though this issue got closed as a red herring.  Here's the error I was getting:

```
--- Looking up irc.eu.freenode.net..
--- Connecting to chat.freenode.net (193.10.255.100) port 6697..
* * Certification info:
*   Subject:
*     OU=Domain Control Validated
*     OU=Gandi Standard Wildcard SSL
*     CN=*.freenode.net
*   Issuer:
*     C=FR
*     ST=Paris
*     L=Paris
*     O=Gandi
*     CN=Gandi Standard SSL CA 2
*   Public key algorithm: rsaEncryption (2048 bits)
*   Sign algorithm sha256WithRSAEncryption
*   Valid since Dec 14 00:00:00 2015 GM to Feb 16 23:59:59 2017 GM
* * Cipher info:
*   Version: TLSv1/SSLv3, cipher DHE-RSA-AES256-GCM-SHA384 (256 bits)
--- Connection failed. Error: * Verify E: Failed to validate hostname? (-1)
```

Turning off "Use SSL" solved this.  (Of course, I'd like to figure out how to get SSL working properly, but at least for now I can join channels on Freenode again.)

**Comment by TingPing** [comment]
@kfogel There is no issue with the client; The * wildcard only matches one level so `*.freenode.net` does not match `irc.eu.freenode.net`. The solution is bother freenode to fix their certificate or connect to `chat.freenode.net` directly.

**Comment by kfogel** [comment]
Thanks @TingPing for responding, and for taking the time to look at the error message.

I've re-enabled TLS after specifying `chat.freenode.net` and `irc.freenode.net` as the only servers, and it works now.  (I have no idea why I was connecting to `irc.eu.freenode.net` anyway; my configuration files are ancient, so that was probably some workaround from when I was traveling in Europe one time or something.)

It was interesting to watch the `F` parameter go from "11" to "15" when I re-enabled TLS -- I guess it's some sort of bitmask.
