### ISSUE TITLE
HexChat can't whois Russian nicknames.

### ISSUE THREAD

**Issue by Kaodominch** [hexchat/hexchat#1375]
As said in the tittle, seems like HexChat cannot whois Russian nicknames. Just gives me nothing but a message saying "End of WHOIS list.".

Windows 7 Home Premium. 64-bit. I have my interface in English and only Russian locale

**Comment by TingPing** [comment]
Well that is the servers problem not HexChats it sounds like. What network supports russian nicks so I can test?

**Comment by Kaodominch** [comment]
No, it's not the network's problem. I can whois in other clients like KVirc, but not HexChat.

Try irc.wenet.ru for testing.

**Comment by TingPing** [comment]
Works fine here.

**Comment by TingPing** [comment]
Do note that I am on the latest [test build](https://dl.hexchat.net/hexchat/testing/) which has done some work on encodings. It is possible you are using an encoding that does not match what the server expects.

Since this network is terrible and uses like 8 encodings depending on the port, none of which are utf8 which is what HexChat defaults to this seems like the likely cause.

**Comment by Kaodominch** [comment]
Huh, that actually does work if you change it. Weird, I'm pretty sure I've done that before and did nothing. But oh well, thank you very much.
