### ISSUE TITLE
Plain text saving of passwords on disk

### ISSUE THREAD

**Issue by PureCS** [hexchat/hexchat#1385]
I recently came across the fact that network passwords are saved in plain-text on the local system. Are there any plans to address this security risk?

**Comment by PureCS** [comment]
I have found a similar thing answered before, bleh.

**Comment by TingPing** [comment]
For the record that issue was #75. But my opinions are not the same as the previous developers.

I am all for implementing platform specific keyring integration, but somebody needs to make an abstraction around that and 3 implementations of it (Windows, Libsecret, OSX) including migration of old passwords and ideally some way to export them. So far we have gotten patches for one incomplete implementation of libsecret.

**Comment by PureCS** [comment]
I agree completely with you, a master password system would work perfectly in hand with SSL. It might not be completely secure but it would be damn good.

**Comment by Arnavion** [comment]
It is still a duplicate of #75
