### ISSUE TITLE
HexChat not working anymore. :(

### ISSUE THREAD

**Issue by Archangel45** [hexchat/hexchat#1411]
Is there a problem on why HexChat isn't working anymore? I'm basically using Windows 8.1 x64 and when you click at the client, it doesn't come out. I tried using hexchat-test at cmd but it says "hexchat-test has stopped working". Welp, I tried uninstalling and reinstalling it, it still doesn't work. Even I tried to force uninstall it and reinstall, it's still doesn't work at all. I did do different versions, and the same thing happened. Is there a reason? I really tried everything I did.

**Comment by Poorchop** [comment]
I don't know what you mean by "force uninstall" but uninstalling HexChat doesn't wipe your configs. Assuming you are on Windows, you have to manually delete your config folder (`%APPDATA%\HexChat`). You can try using Visual Studio to debug so that you get some useful information about the crash.

I'm also guessing you meant "hexchat-text" instead of "hexchat-test." I would suggest just backing up your config to some other location and then deleting it from from the location I typed above, after which you should try to relaunch HexChat. I'm using it on the same platform without and issues so the error is probably on your end.

**Comment by TingPing** [comment]
Possibly delete `%appdata%\hexchat\scrollback`. Common case of crash on start.
