### ISSUE TITLE
VS2015 support

### ISSUE THREAD

**Issue by jasonwilliams200OK** [hexchat/hexchat#1481]
Since VS2015 supports C99 (+partly C11) and generate binaries for Windows XP-10, please update the vcxproj and sln files to make them compile with VS2015 toolset and remove the guard headers etc. for old version. A free Community edition of VS2015 is available for OSS projects, which is equivalent to Professional edition.
Besides, AppVeyor also supports VS2015 in all the images. You can configure the CI to store the build artifacts and use the generated binaries, if you don't want to install VS2015 locally.

**Comment by TingPing** [comment]
Work on that is over at https://github.com/hexchat/gtk-win32/tree/2015

**Comment by Arnavion** [comment]
Just to set expectations here:

- More C99 support is not (yet) relevant for GTK2 / HC
- The current binaries work just fine on 7+, including 10; 10-specific bugs notwithstanding.
- HC will not work on XP regardless of whether 2015 is used or not.

Also, hosted CI is not practical to build GTK2 on, which is why we have our own.

(If you're in a hurry you can build GTK2 and HC from the two branches in @TingPing 's comment yourself.)

**Comment by jasonwilliams200OK** [comment]
I am not particularly following the progress of this project. The prospective value from this discussion is more of a high-level awareness (and applicable to all C-based projects on GitHub) that don't waste your time with C89, if MSVCR was the only thing keeping you from C99. Not anymore.

I quickly made a commit upgrading all the project files etc. https://github.com/jasonwilliams200OK/hexchat/commit/2a0aaba16e73ed602cb74f17136fc789c820863e. Currently it fails on the custom commands set in build process because I didn't tried with that particular GTK2 branch.

The point of XP comment was to highlight the fact that many C libs were putting lot of effort to support MSVC with C89 fallback code and POSIX include guards. With VS2015, your code situation may get better (less fragmentation/branching, less `#ifdef _MSC_VER`, no custom `snprintf` definitions etc.) as there is no point in keeping older VC support, when more capable version builds for XP-10. Good to know that you guys are already moved on from XP.

Regarding hosted CI, I later that realized hexchat is using Jenkins. BTW, I have seen many larger projects than hexchat building fine on free AppVeyor instance but YMMV!

**Comment by Arnavion** [comment]
>I quickly made a commit upgrading all the project files

Just changing PlatformToolset from v120 to v140 is not sufficient to get a working HC, as you will find in the (fully functional) 2015 branch you were already linked to which does that and more.

>The point of XP comment was to highlight the fact that many C libs were putting lot of effort to support MSVC ... Good to know that you guys are already moved on from XP.

Yes. We explicitly, deliberately don't support XP. For example https://github.com/hexchat/gtk-win32/blob/f859838/glib/glib-if_nametoindex.patch#L12-L13 although this particular case was only because of a glib bug.

>no custom snprintf definitions etc.

You'll find [one problematic instance](https://github.com/hexchat/gtk-win32/commit/2e186f4#diff-59a1508102fc4efcc899d4e730de9928L35) (the only one? certainly the only one that caused a compile error) already removed in the branch you were already linked to.

>BTW, I have seen many larger projects than hexchat building fine on free AppVeyor instance but YMMV!

The large project in consideration is GTK2, not HC. And it is a bit of a special snowflake in how it needs to be built, so setting up a custom CI is easier. For example it requires msys2 and a few custom packages, and you really don't want to be installing those for every build in an AppVeyor instance when you could just install them once on a VPS.

**Comment by Arnavion** [comment]
Also I should note that the primary reason we're not using 2015 yet is because CPAN Perl doesn't build with it (yet), for reasons documented [here.](http://stackoverflow.com/questions/31150635/build-error-in-visual-studio-in-perlio-h-and-iobuf/31615790#31615790)
