### ISSUE TITLE
Crash Windows 10 MSVCR100.dll missing

### ISSUE THREAD

**Issue by rjdevries** [hexchat/hexchat#1486]
After installing in my new Windows 10, Hexchat starts with the error that MSVCR100.dll is missing. And after adding the file to Windows it complains that MSVCR120.dll is missing. And maybe more to come.

After closing the errors, Hexchat wil not start. :-(

**Comment by TingPing** [comment]
HexChat 2.10.x only requires *MSVCR120.dll*. If you install HexChat normally (not portable mode) it will download and install it for you, otherwise you can install it from [Microsoft.com](https://www.microsoft.com/en-us/download/details.aspx?id=40784). I presume the *MSVCR100.dll* issue is because you keep portable installs over top of older ones leaving old plugins.

(This issue has been reported a dozen times with the same response already, please use search)

**Comment by rjdevries** [comment]
I did fix it by installing Visual C++ Redistributable Packages for Visual Studio 2013
To be clear, I did not use the portable version and the installation was not over a older version. I installed it on a new Windows 10 PC.

**Comment by TingPing** [comment]
Very strange, the HexChat installer certainly downloads it.
