### ISSUE TITLE
Log is displayed with wide gaps in between along duplicated timestamp

### ISSUE THREAD

**Issue by Ghasan** [hexchat/hexchat#1642]
I am using Windows 10 Pro x64, and just installed the latest version of HexChat 2.12.0 x64. I noticed that the message log loaded is displayed with wide gaps in between, and while the gap is empty (contains no text), the timestamp looks to be a duplicate of the adjacent message.

![Demo](http://s30.postimg.org/fmkbo7zqp/Capture.png)

**Comment by TingPing** [comment]
Previous versions of HexChat added tons of newlines in the scrollback and just ignored them, so 2.12.0 actually fixed that and will no longer add extra newlines but it also doesn't ignore them anymore so old scrollback appears broken. The easiest solution is to just delete old scrollback or wait for new messages to overwrite the old otherwise you can manually edit the files.

**Comment by Arnavion** [comment]
```powershell
gci -re $env:APPDATA\HexChat\scrollback | ?{ $_ -is [System.IO.FileInfo] } | %{
    $filename = $_.FullName
    $contents = gc $filename | ?{ $_ }
    $contents > $filename
}
```

Backup everything first. I take no responsibility if you screw something up, etc.

**Comment by Ghasan** [comment]
Oh, okay then. I think I will just wait for the new messages to fix this :smile: Thanks, Arnavion, but I prefer just to leave it alone.
