### ISSUE TITLE
Global gtk theme works in 2.10.2 but breaks when I upgrade 2.12.1

### ISSUE THREAD

**Issue by nkmathew** [hexchat/hexchat#1742]
My global `gtkrc-2.0` file:

```ruby
# Auto-written by gtk2_prefs. Do not edit.

gtk-theme-name = "Human"
style "user-font"
{
	font_name="Segoe UI 9"
}
widget_class "*" style "user-font"
```

Shot with 2.10.2 installed:
![](http://image.prntscr.com/image/77f93695b81142f0a6fcb280061dbeef.png)

Now if I install 2.12.1 I get this:
![](http://image.prntscr.com/image/631e7ab2d25448f59e84b6c38ba3c6e6.png)

**Comment by TingPing** [comment]
And where is the Human theme installed? It would go into `<installdir>/share/themes`.

**Comment by nkmathew** [comment]
I have both themes in:

```
C:\Program Files\HexChat\share\themes\Human\gtk-2.0\gtkrc
C:\Program Files (x86)\X-Chat 2\share\themes\Human\gtk-2.0\gtkrc
```
They are being loaded just not rendering the theme as you'd expect

X-Chat 2 does it best:

![screenshot_1](https://cloud.githubusercontent.com/assets/5522822/15985336/7d2a8924-2ff2-11e6-96b0-7296fb9e45c9.png)

The new one not so much:

![screenshot_2](https://cloud.githubusercontent.com/assets/5522822/15985342/9945b6b0-2ff2-11e6-8823-860f5d90bbd5.png)

The old version to an  extent:

![screenshot_3](https://cloud.githubusercontent.com/assets/5522822/15985346/b244050e-2ff2-11e6-90cb-c030b08921f2.png)

**Comment by TingPing** [comment]
- The old setup for hexchat shoved the windows theme into `etc\gtk-2.0\gtkrc` so your modification to it was just combining the two themes. Now it properly uses the themes directory but you could recombine them manually.
- The Human theme depends upon a theme engine that HexChat does not provide (it only provides pixbuf) so it will never render properly.

**Comment by nkmathew** [comment]
I don't really care too much about Human's cool look, I used to install it to avoid the blocked/grooved widgets in default gtk ui. Is there a way to change this in the new version?

**Comment by TingPing** [comment]
> the blocked/grooved widgets in default gtk ui.

Could you be more specific? The screenshot you showed of HexChat 2.10 is basically the default theme so if you were fine with that I don't see a problem.

**Comment by nkmathew** [comment]
That's what I don't want. I need it to look like a native windows app with normal looking input boxes and buttons

**Comment by TingPing** [comment]
It looks fairly native to me...

**Comment by nkmathew** [comment]
Help me out here, I can't stand default gtk. Is there a theme that works with 2.12.1?

**Comment by TingPing** [comment]
I'm not sure we are on the same page here, this is the default theme:

![](https://camo.githubusercontent.com/d58d0bffe7dd2b0ced315829da4dd8ba173aa011/687474703a2f2f696d6167652e70726e747363722e636f6d2f696d6167652f37376639333639356238313134326630613666636232383030363164626565662e706e67)

Simply delete your broken configuration and that is what you get. If you say that doesn't look like the Windows theme I don't know...

**Comment by nkmathew** [comment]
I'm speaking of the newest version, 2.12.1, the one you say has a new engine that doesn't support all the features of the Human theme. The version above is the previous that I was updating from which looks ok. The new look is what I have a problem with:

![](http://image.prntscr.com/image/bad648daad384416a47e06239ddeae27.png)

**Comment by Poorchop** [comment]
The very first screenshot you posted is just the default gtk theme that is bundled with the Windows installation. As it was mentioned, your Human theme was never working at all, not even with 2.10. If you haven't overridden the default bundled theme, then just delete your global gtk theme and the one that you placed in the HexChat directory. If it's still not working, then reinstall HexChat and delete `C:\Program Files\HexChat` if it's still left over after first uninstalling.

I'm using a custom GTK theme in the latest version and it's working fine for me, so the fact that the Human theme isn't working on your end isn't a bug in HexChat. I'm still kind of confused about what it is exactly that you're trying to achieve but you can ask on IRC since it will be quicker to troubleshoot there.

**Comment by TingPing** [comment]
Specifically just delete `C:\Program Files\HexChat\etc` and everything will work fine.

**Comment by nkmathew** [comment]
I did delete the themes that I had copied to hexchat's share folder together with my `.gtrkrc-2.0` and got the default, okay look I had before.

Strange thing is if I restore my `.gtkrc-2.0` with no theme files in my computer except the default "MS-Windows" one bundled with the installer I get the ugly gtk version of it.

Screencast:

![recording](https://cloud.githubusercontent.com/assets/5522822/15986775/bb71ab0a-3019-11e6-9387-4574451863fa.gif)


I know this thread has gone on longer than it should have. I'd just like to know what you make of this behaviour then I'll close this issue, I can live without the rc file

**Comment by TingPing** [comment]
Ah yea `.gtkrc-2.0` in the home dir obviously will break it too, obviously just stop referencing bogus themes and it should be fine.

**Comment by nkmathew** [comment]
Thank you, I was almost going crazy with this whole thing. Can you point me to gtk themes that don't break this new version? @PoorChop what theme are you using?

**Comment by Poorchop** [comment]
It's just a simple dark theme made by somebody who used to idle in #hexchat. I don't think you'd like it since it still has the GTK buttons that you dislike. I don't think HexChat breaks any existing GTK themes though - if it worked in an older version, it will work in the current builds.

![untitled-1](https://cloud.githubusercontent.com/assets/5256208/15986902/9cfe2c42-2fe3-11e6-82b7-db98acd7b7d1.png)
