### ISSUE TITLE
Issues with perl installs

### ISSUE THREAD

**Issue by Yoposoc** [hexchat/hexchat#1981]
It seems like hexchat only recognizes perl 5.20 installs, but perl is currently at 5.24. Is there a way to make it recognize the 5.24 dll, since the 5.20 dll isn't available to download separately?
![Image](https://my.mixtape.moe/avltvz.png)

**Comment by TingPing** [comment]
No it has to be built against the same version of Perl. The reason we haven't updated Perl is because they are absolutely terrible at supporting building against VS and it has taken them years to fix VS2015 support. There is some upstream bug report but I don't have the link off hand.

> since the 5.20 dll isn't available to download separately?

Well the dialog literally links to a download.

**Comment by Yoposoc** [comment]
>Well the dialog literally links to a download.
whoops.... (´・ω・｀)
