### ISSUE TITLE
Publish hexchat in the Windows Store

### ISSUE THREAD

**Issue by rogersachan** [hexchat/hexchat#2010]
The Windows Store now supports publishing Win32 Desktop apps with little
or no code change using the Windows Desktop Bridge. Taking advantage of
the Windows Desktop Bridge and Distributing through the Windows Store
also  provides simplified options for  automated updates, easy install
and uninstall, and provides a new distribution path for folks who may
have not found hexchat before.

#### Links / References
* https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-root
* https://developer.microsoft.com/en-us/windows/bridges/desktop

**Comment by TingPing** [comment]
We will still have to make normal releases for a long time to come since we have a lot of Windows 7 users, support portable installs, and some subset of the userbase will never touch the Windows Store in the first place.

I imagine UWP will also impose some limitations so we probably can't use the system Python (not the biggest blocker honestly).

Anyway this is rather unlikely as we don't have much active development on Windows so it is up to @tomek if he wants to play with it or not.

**Comment by rogersachan** [comment]
You aren't forced to use the system Python, the convert simply puts the
application in a container. The converter considered a superset of UWP
since it has access to UWP APIs and Win32 APIs.

**Comment by xshotD** [comment]
Actually, this would kinda affect things.

I really do not know how scripting (kind of a critical part of hexchat) would work in this scenario (besides C scripts but still), because it is in a container and most likely would not have access to things such as Lua, Python, and other things needed.

I'm also not too sure who uses the Store for things like this.

**Comment by TingPing** [comment]
We already bundle lua so I suspect that continues to just work, we can bundle Python if needed.

**Comment by xshotD** [comment]
Ah. Well, the last point/opinion still stands :P

**Comment by TingPing** [comment]
@xshotD Oh, nobody wants to use the store but Microsoft will force people to on a version of windows now, and give it a few more years and it will be a completely locked down platform =)

**Comment by xshotD** [comment]
That idea is plausible...

**Comment by rogersachan** [comment]
In the past few days the following OSS apps have become available on the store: Inkscape, Krita, Telegram, and Kodi.

P.S. Blender has plans to make their program available on the store, and AFAIK it bundles python as a whole with it.

**Comment by rogersachan** [comment]
@TingPing Who are the win32 maintainers?

**Comment by TingPing** [comment]
Well the few devs that use Windows I am confident have no interest in this.

**Comment by rogersachan** [comment]
@TingPing It doesn't hurt to ask.

**Comment by Arnavion** [comment]
His confidence is correctly placed.

**Comment by xshotD** [comment]
I just thought about this, and I think it would be a good idea for Windows 10 SKUs Cloud/S

**Comment by bryanloeper** [comment]
Just came across this and thought I'd ask if it's legit considering the direction of this thread:

https://www.microsoft.com/en-us/store/p/hexchat/9nrrbgttm4j2?rtc=1

**Comment by learn-more** [comment]
I see a lot of volunteers here.
@rogersachan , @tilda, @bryanloeper

**Comment by tilda** [comment]
@bryanloeper Seems like it. @TingPing can you verify this?

**Comment by TingPing** [comment]
Yup it is legit, also note it is free they just don't have a "donate" option.
