### ISSUE TITLE
Missing exception handling in scripting plugins

### ISSUE THREAD

**Issue by GaryMatthews** [hexchat/hexchat#2083]
According to the docs there is no method of handling plugin script errors and other exceptions. all errors result in a total crash of the entire client. i am using javascript plugin and try {} catch(e) {} does not work. there are lots of complaints about scripts crashing for other languages also. when is exception handling going to be added?

**Comment by TingPing** [comment]
The JavaScript plugin is unofficial and not supported.

**Comment by GaryMatthews** [comment]
why include it in the plugins folder and scripting documentation? it also states in the summery that javascript is one of scripting languages 'supported'?

**Comment by TingPing** [comment]
No it doesn't:

> There are multiple scripting languages supported by HexChat but currently only Python (2.7 & 3.5), Perl (5.20), and Lua are officially supported with Lua being the recommended option.

Source: https://hexchat.readthedocs.io/en/latest/developers.html#scripting

> The javascript plugin does not come with HexChat, more information on it can be found Here
This page is simply for hosting its API docs and is a work in progress.

Source: https://hexchat.readthedocs.io/en/latest/script_javascript.html


Anyway ignoring that, I honestly have no clue what your complaint is for, none of the API can throw exceptions because it uses return values to indicate failure. General failure does not result in a crash you are probably doing something particularly bad. You could argue the plugin should handle that but that has overhead and you will always be able to cause a crash if you try.
