### ISSUE TITLE
HexChat 2.14.0 crashes when trying to use GTK theme

### ISSUE THREAD

**Issue by edillingham** [hexchat/hexchat#2140]
After upgrading to 2.14.0, HexChat crashes immediately on startup when using a custom GTK theme.  Theme was installed via the instructions found at http://hexchat.readthedocs.io/en/latest/appearance.html.  Removing the theme fixes the problem.

**Comment by catlinman** [comment]
Can reproduce and confirm this as well. Furthermore, the new version seems to have changed the way styles and custom GTK themes are handled as many of the previous working elements now have different colors. In my theme for example, the chat input box previously had a yellow border. Now instead of having that when selected, the entire chat input field itself receives this color. I don't think this change is intentional as it breaks every custom theme I have tried so far.

I have attached a before and after image of my theme as you can see below. If someone wants to test it out with that theme you can [click here to navigate to the repository](https://github.com/catlinman/nekoconfig/tree/master/hexchat).

Before installing the new version. Pay attention to the background, scrollbar and input box colors.
![Before](https://user-images.githubusercontent.com/1859270/37359843-edc17f36-26ee-11e8-8c4e-72a52528016e.png)

After the update breaking GTK themes. Ignore switch from tree to list view.
![After](https://user-images.githubusercontent.com/1859270/37360048-70626018-26ef-11e8-984c-0fd552b211bb.png)

**Comment by TingPing** [comment]
I forgot to build the pixmap theme engine which is @catlinman's issue and I'll fix soon. None of this should ever cause a crash though.

**Comment by TingPing** [comment]
This is fixed in 2.14.1
