### ISSUE TITLE
Import/Export settings capability

### ISSUE THREAD

**Issue by ghost** [hexchat/hexchat#217]
hexchat.c/fe-gtk.c (de)initialization procedures might be worth to look at for hints.

**Comment by Arnavion** [comment]
Users are okay with copying ~/.config/hexchat / %APPDATA%\HexChat around.

**Comment by CapsAdmin** [comment]
I tried to copy the hexchat config folder from windows to linux which doesn't work well. Turns out it was a line ending issue so I had to do ``find . -type f -exec dos2unix {} \;`` in the config folder on linux after copying from windows.

Just thought I'd mention this since I found this on google when searching for the problem.
