### ISSUE TITLE
Python 3.6 scripting does not install on Windows 10

### ISSUE THREAD

**Issue by eacpereira** [hexchat/hexchat#2171]
I realized I needed python scripting to fix my dead key problem, so I uninstalled Hexchat (via remove programs) and reinstalled it, selecting Python 3 scripting for install. However, the Python 3 dll does not install, even after a restart.
![image](https://user-images.githubusercontent.com/921547/38455678-a24762aa-3a49-11e8-958f-ec74409fd551.png) I tried this uninstall-reinstall cycle twice, to make sure I wasn't forgetting to select the installation of Python scripting, but the result was the same.

I'm on Windows 10, using Hexchat 2.14.1.

**Comment by eren-kemer** [comment]
Can confirm, same version, Windows 10 EXE Installer.

**Comment by TingPing** [comment]
> Further info: when I used the HexChat installer it launched a Python 3.5 installer, which I cancelled because I already have 3.6.

Well then you were installing an old version of HexChat.

**Comment by OrangeDog** [comment]
> an old version of HexChat.
Indeed, the auto-updater just ran, and now the Python scripting works fine.

**Comment by harl** [comment]
I'm in the same position as OrangeDog and as the title implies, so I'll just add my question to this issue.

My HexChat is up to date, my Python is "up to date" (at version 3.9.7) and its path is in the PATH variable.
I get the same error message ("The specified module could not be found.").
Do I need to downgrade Python to 3.6 or what else do I need to do so that the Python plugin can be loaded?

**Comment by TingPing** [comment]
>  Do I need to downgrade Python to 3.6 or what else do I need to do so that the Python plugin can be loaded?

You must use the same major version, 3.6.

**Comment by OrangeDog** [comment]
@TingPing 3.6 is a minor version. The major version is 3.
