### ISSUE TITLE
Already encoded URLs are double encoded (regression in 2.16.0)

### ISSUE THREAD

**Issue by lzaoral** [hexchat/hexchat#2659]
If you send URL that is already encoded (e.g. [https://en.wikipedia.org/wiki/%22](https://en.wikipedia.org/wiki/%22)) and open it by clicking or by the "Open link in Browser" context menu entry, it will be encoded once again breaking the link (e.g. [https://en.wikipedia.org/wiki/%2522](https://en.wikipedia.org/wiki/%2522)).

Occurs on Arch Linux with Firefox 95 and Hexchat 2.16.0. If I downgrade to 2.14.3 everything works as expected and the link above remains unchanged.

edit: typo

**Comment by qwertfisch** [comment]
@TingPing The issue seems not to be fixed. I just tested with Hexchat 2.16.1 (Flatpak version) and can confirm that URLs will still be double-encoded on “Open link in browser” or simply clicking on the URL, thus breaking the link. Tested browsers are Firefox 114 and Chromium 114 on Linux Mint 21.1 Cinnamon.

Could you reopen the issue, or better have a look at the bug again?

**Comment by TingPing** [comment]
It was changed further in c48afe3799e648e0ded2bf07deeb082028b6c5ac
