### ISSUE TITLE
Selection copy behavior wrong/confusing

### ISSUE THREAD

**Issue by haarp** [hexchat/hexchat#541]
Hey. I realize that Xchat didn't do this very well either, but Hexchat seems to have broken it further.

I cannot select text and ctrl+c, it's shift+ctrl+c now. Why was this changed? It's annoying because every other application on people's systems uses plain ctrl+c (except for shells, but we know the reason for that).
The right-click menu also requires the user to enter a submenu to reach "copy selection", while it would be much better off as its own entry in the root right-click menu, imho (along with a few other entries like search).

Selecting text on Linux also does not put the text in the selection buffer anymore by default, which is also sorely missed by me.
There is of course the "Automatically copy selected text" option. But in addition to copying into the selection buffer (the select/middle click thing on Linux) like expected, it also copies into the paste buffer (ctrl+c, ctrl+v), which is really quite confusing and annoying, because it will replace your paste whenever you select anything.

Hexchat is a great client, and I appreciate your work on it. But these are usability issues which really shouldn't exist.

**Comment by Traumflug** [comment]
Being late to this party, I'm confused as well. Reading the above comments I learned you can select text in the message view as well as in the input line. Surprise, surprise!

I think the confusion comes from the fact that message view and input box are two different views. Technically that's entirely fine, but it isn't intuitive.

Imagine you fire up your word processor and write something. Occasionally you hit enter. Text grows and starts to scroll upwards. You select something farther above, continue to write at the end. All this is very similar to how a chat window looks and is used.

Accordingly, users also expect a chat window to behave similarly. Technically this means, these two views, message view and input box, should behave like one view. Making a selection in the upper removes the selection from the lower and vice versa. Hitting Ctrl-C copies the selection, no matter which of these views has focus. Same for copy/paste by mouse button.

my $0.02

**Comment by Arnavion** [comment]
Chat clients aren't word processors. The two views *are* separate. Many (all?) chat applications allow selecting text in the two views independently. Your analogy is invalid.

HexChat is different only in that the input box retains keyboard focus even if you click on the channel view. As a result, Ctrl-C always applies to the selection in the input box, and thus we have a separate shortcut Ctrl-Shift-C that always applies to the selection in the channel view.

**Comment by Traumflug** [comment]
Ah, OK. Just because other chat applications are counterintuitive, HexChat feels a need to do the same. That's disappointing.

I see no point in having more than one selection, because there's only one buffer. In fact it makes things worse, because one can no longer figure what's in the copy/paste buffer by looking at what's selected.

**Comment by haarp** [comment]
I'd actually claim that other chat applications are more intuitive.

You select something -> it ends in the middle-click buffer (on Linux)
You select something, press ctrl+c -> it ends up in the clipboard

That's intuitive.

Whereas in Hexchat, you select some chat log, press ctrl+c > Middle-click buffer remains unchanged, and on the off-chance that you just happened to have something in the input box selected, that ends up in the clipboard.

It just doesn't make sense to distinguish the inpot box from the message log. Intuitively, the most recently made selection, no matter if it's in the input box or elsewhere, should be used. That's how every other chat program does it.

It wouldn't be quite as bad if Hexchat at least offered a "copy" item in the right click menu on the chat log, but that's also missing :(

**Comment by Arnavion** [comment]
>Ah, OK. Just because other chat applications are counterintuitive, HexChat feels a need to do the same. That's disappointing.

Yes, HC would rather be consistent with other chat applications than other arbitrary applications you'd want it to be consistent with...

>It just doesn't make sense to distinguish the input box from the message log.

The whole reason behind HC's behavior is that it has the copy-on-selection behavior for the channel view that does not require you to press anything to copy. The point is that if you select something from the channel view to copy it, it's better the input box doesn't lose focus because there's nothing else you could've done on the channel view anyway, so why bother removing focus from the input box. With copy-on-select disabled, again the only keypress you can do is ctrl-c, so instead of removing focus from the input box we made a separate shortcut ctrl-shift-c for manually copying the channel view selection.

The only reason this bug is left open is because of your original problem that the copy-on-selection overwrites both the middle-click buffer and the ctrl-v buffer. The actual behavior when copy-on-selection is enabled or disabled, and the keyboard shortcuts involved, are by design and not going to change.

**Comment by TingPing** [comment]
>It wouldn't be quite as bad if Hexchat at least offered a "copy" item in the right click menu on the chat log, but that's also missing :(

No its there but its under *Window* since its the same menu as the menubar.

Personally I see no reason that two copy buffers still exist, one day the major DEs will remove such functionality I assume.

**Comment by Traumflug** [comment]
Sometimes open source applications are outright hopeless. *Zero* listening to the users.

**Comment by deckblad** [comment]
Auto-copy of selected text is broken. It should work like mIRC:
Correct: 
User selects text
mIRC copies selected text to clipboard
mIRC deselects previously selected text.

Incorrect:
User selects text in hexchat channel buffer
Hexchat copies selected text to clipboard
Hextchat leaves buffer text selected
User switches to a different program
User copies some other text to clipboard
User switches back to Hexchat
Hexchat copies originally selected text to clipboard
Hexchat leaves selection on text in buffer
User pastes what they think will be the text from another program, hits enter, is laughed at by friends for posting text from the channel to the channel.
Hexchat stops caring and dies alone.
