### ISSUE TITLE
Shift+Click on server tab closes it

### ISSUE THREAD

**Issue by RyanCordell** [hexchat/hexchat#918]
There is no reason such hardcoded shortcuts should be there in the first place. Either these should be removed entirely or exposed to the user such that they can be disabled and/or modified at will, would be much appreciated.

I've had one too many moments where I was trying to talk to someone and ended up closing tabs thanks to holding down shift.

**Comment by njsmith** [comment]
My wife's been having trouble with hexchat randomly closing channels for months. Today we finally figured out that the reason: it's happening when her palm happens to brush the laptop's touchpad and it mis-registers a click, at the same time that she happens to be pressing the shift key to type some capital letter.

Since we cannot replace her palm and it would be difficult to replace the laptop, we would very much appreciate some way to disable this shift-click behavior.

**Comment by vlakoff** [comment]
I do have to mention https://xkcd.com/1172/ !

**Comment by nkichukov** [comment]
I've certainly missed the removal of shift-left mouse click to close tabs. I have been used to this from so many moons ago. This is a breaking change for me. I tried to work around this by configuring accelerators from the keyboard shortcuts preferences, but this was not something that could be configured there. I've asked a few times in the IRC channel, no response.

Because I am running source based distribution, for now I will continue to maintain a 'patched' version of hexchat that basically reverses the change from https://github.com/hexchat/hexchat/commit/dc483b234253c3a72e006e0e15d81c73b8b2a511.patch .

Please, consider reverting this into mainline. It is a handy function to have. I certainly missed that a lot!
